### ISSUE TITLE
Seria possível adicionar validação nova para verificar formato do CEP

### ISSUE THREAD

**Issue by wallacemaxters** [LaravelLegends/pt-br-validator#1]
Ainda não tive tempo de pesquisar se o formato do CEP em todo o país possui o mesmo padrão `00.000-000`, mas estou pensando na possibilidade de adicionar tal validação à biblioteca.

A ideia era criar algo como:
```php
$dados = ['cep' => '32.400-000'];
Validator::make($dados, ['cep' => 'required|formato_cep']);
```

**Comment by wallacemaxters** [comment]
Criar com sucesso na versão #5.1.1

O próximo alvo é fazer a atualização para o #4.2

**Comment by crispossa** [comment]
Adicionei no Readme a explicação da regra.

**Comment by wallacemaxters** [comment]
@crispossa sim, sim, o mais rápido possível farei. Ultimamente tem sido difícil me dedicar, mas no dia-a-dia também acabo usando a biblioteca.

Obrigado pela participação.
