### ISSUE TITLE
Prover as traduções de validações default do laravel em pt-br

### ISSUE THREAD

**Issue by dann95** [LaravelLegends/pt-br-validator#21]
Olá devs, o que vocês acham de prover a tradução das validações default do laravel ex: int, email, etc, etc.. através desse service provider? se concordarem, posso fazer o PR.

**Comment by wallacemaxters** [comment]
Eu acho que isso já existe, não? Tem um repositório que tem isso. 

Não sei se seria o ideal colocar na mesma biblioteca, caso realmente formos fazer algo do tipo.

**Comment by dann95** [comment]
Os repositórios que existem são tipo "copie e cole", n é algo via ServiceProvider, e soa meio coerente se a pessoa vai validar coisas brasileiras, e as mensagens de validação estão em pt_BR, imagine a hipótese de colocar o as rules de validação
```php
[
//...
'cep' => ['required','cep'] // ou 'required|cep'
//..
]
````

se o usuário não inserir o cep vai aparecer "field is required", e se não tiver certo o cep, uma msg em pt_BR..

Também há o caso de algum estrangeiro querer usar a LIB, e ter as mensagens em pt_BR, seria legal criar um namespace e adicionar traduções em inglês..

**Comment by dann95** [comment]
Lembrando que copiar os stubs de tradução pode ser algo "opcional" dando vendor publish com a tag do ServiceProvider.

**Comment by dann95** [comment]
E se houver um arquivo de config, permitiria o dev customizar as mensagens, uma vez que hoje elas só tem uma origem.. https://github.com/LaravelLegends/pt-br-validator/blob/master/src/pt-br-validator/ValidatorProvider.php#L38

**Comment by dann95** [comment]
ping @wallacemaxters
