### ISSUE TITLE
Validação de telefone com erro nos formatos especificados 

### ISSUE THREAD

**Issue by ribsousa** [LaravelLegends/pt-br-validator#24]
Olá pessoal!

Bom trabalho

Eu testei as formas de validar telefone celular:
(99)99999-9999 e (99)9999-9999 sem espaço funcionam
(99) 99999-9999 e (99) 9999-9999 com espaço não funcionam

Outra coisa não acham que deveria verificar somente os números sem parênteses, espaço e hífen?
Porque no meu ver isso é apenas formatação e não necessitamos verificar isso ou inserir no bd. Resolvemos isso com uma aplicando uma simples máscara no campo.

**Comment by wallacemaxters** [comment]
Olá, qual é a versão do Laravel que você utiliza?

**Comment by wallacemaxters** [comment]
> Outra coisa não acham que deveria verificar somente os números sem parênteses, espaço e hífen?

Eu acho que não faria sentido. Se for pra inserir apenas o telefone sem os caracteres, você não precisaria da minha validação. Bastaria apensar usar algo como `size:8` para identificar a quantidade de números presente nos campos.

**Comment by ribsousa** [comment]
Olá! estou usnado a versão 5.4

**Comment by renanBritz** [comment]
Olá. A validação "celular_com_ddd" não está validando o formato (99) 9999-9999. Porém, valida o formato (99)9999-9999. Sem espaço entre o DDD e número.

É possível verificar? Obrigado.

**Comment by roncalli-daniel** [comment]
Percebi que a validação do celular com DDD foi realizada mas não foi versionada, por isso não está funcionando na versão 5.1.4 (atual até esse comentário).

Uma alternativa é alterar o composer para baixar a versão da branch master.

Para isso basta alterar o require desse biblioteca no composer.json 
`"laravellegends/pt-br-validator": "dev-master"`

e depois rodar `composer update`

**Comment by wallacemaxters** [comment]
Opa. Eu vou dar uma olhada nisso assim que tiver um tempinho
