### ISSUE TITLE
BadMethodCallException ao criar uma nova rule

### ISSUE THREAD

**Issue by TiagoEspanha** [LaravelLegends/pt-br-validator#26]
Precisei criar uma nova regra de validação após importar a lib, porém está estourando o BadMethodCallException. 

Como eu posso adicionar novas regras, já que o modo tradicional do Laravel (make:rule) não funciona?

Obrigado

**Comment by TiagoEspanha** [comment]
Nada?

**Comment by wallacemaxters** [comment]
Opa, beleza?

Poderia dar mais informações sobre o erro?

Adicione o backtrace do arquivo de log ou o que foi exibido na página. Sem o log, fica um pouquinho complicado
