### ISSUE TITLE
[dúvida] Validação condicional

### ISSUE THREAD

**Issue by thicsilva** [LaravelLegends/pt-br-validator#27]
É possível fazer a validação de um campo de acordo com a um select? Pergunto isso pois nas validações padrão do laravel temos por exemplo o required_if, e como em alguns sistemas são utilizados o mesmo campo para CPF/CNPJ, não sei como poderia fazer para validar utilizando a biblioteca.

**Comment by wallacemaxters** [comment]
Bem, eu geralmente não gosto de usar o mesmo campo. Quer dizer, visualmente para o usuário eu deixo parecendo "o mesmo campo", mas no plano de fundo eu troco de acordo com uma validação, trocando o input.

Acho que caberia uma validação mais ou menos assim:

```
return [
    'tipo_pessoa' => 'required|in:F,J',
    'cpf'         => 'required_if:tipo_pessoa,F|formato_cpf',
    'cnpj'        => 'required_if:tipo_pessoa,J|formato_cnpj'
];
```

No controller:

```
$cpf_cnpj = ($request->tipo_pessoa === 'F') ? $request->cnpj : $request->cpf;
```

**Comment by thicsilva** [comment]
Agradeço o retorno!
