### ISSUE TITLE
Erro: "Class 'App\Http\Controllers\Validator' not found"

### ISSUE THREAD

**Issue by syond** [LaravelLegends/pt-br-validator#29]
Bom dia.

Não consegui utilizar o Validator no Laravel 5.8.

`Class 'App\Http\Controllers\Validator' not found`

Instalei seguindo o README. Configurei o App.php colocando o código no Providers:

`LaravelLegends\PtBrValidator\ValidatorProvider::class,`

**Comment by wallacemaxters** [comment]
Você colocou a barra antes do `Validator` quando usou?

Porque ele está tentando resolver o nome da classe a partir do `namespace` do seu controle.
