### ISSUE TITLE
Add Support to Laravel 6

### ISSUE THREAD

**Issue by lemosluan** [LaravelLegends/pt-br-validator#30]
Hello, may you add support to Laravel 6?

**Comment by claudsonm** [comment]
Aberto o PR #31 para adição do suporte.

**Comment by jrmessias** [comment]
Olá, 
Seguindo a documentação, ocorre o seguinte erro:

[InvalidArgumentException]
Could not find package laravellegends/pt-br-validator in a version matching 6.*

Notei que a release existe, porém na instalação via composer está ocorrendo erro.

**Comment by claudsonm** [comment]
É que a release existe apenas aqui no Github, o release ainda não está devidamente publicado no Packagist. Reportei [aqui no PR](https://github.com/LaravelLegends/pt-br-validator/pull/31#issuecomment-538995006).

> Joia. Vi que uma nova tag foi criada aqui no repositório, porém no Packagist (https://packagist.org/packages/laravellegends/pt-br-validator) ela ainda não está disponível.
> 
> Há ainda algo a ser feito para liberar o novo release?

**Comment by wallacemaxters** [comment]
Isso foi resolvido aqui: 
https://github.com/LaravelLegends/pt-br-validator/pull/31
