### ISSUE TITLE
Não compatível com Laravel 7

### ISSUE THREAD

**Issue by AlexAlexandre** [LaravelLegends/pt-br-validator#36]
Pessoa, tentei instalar a lib em um projeto que comecei hoje, porém por se tratar da versão 7 do laravel não foi possível. 

Vocês tem alguma previsão de fazer esta atualização?

**Comment by wallacemaxters** [comment]
Bom dia, 

Vou tentar dar uma olhada nisso nesse sábado sem falta.

**Comment by AlexAlexandre** [comment]
Beleza amigo, obrigado pelo retorno.
Se eu puder ser útil em alguma coisa estou a disposição.

**Comment by wallacemaxters** [comment]
Meio atrasado, mas criei a tag para versão 7.0.
