### ISSUE TITLE
Ordem do carregamento do service provider ou múltiplos resolvers

### ISSUE THREAD

**Issue by thiagogomesverissimo** [LaravelLegends/pt-br-validator#38]
## Problema

Do jeito que está implementado, o service provider dessa biblioteca impede que se use outra biblioteca com validação customizada, há uma discussão sobre a questão em:
https://laracasts.com/discuss/channels/general-discussion/resolving-multiple-custom-validators

Isto é,  se tivermos dois ou mais services providers que chamam `$this->app['validator']->resolver(...)` no boot(), valerá a última chamada, isto é, somente as validações customizadas do último service provider que chamou `$this->app['validator']->resolver(...)` estarão disponíveis para uso.

## Possível solução

Na documentação mais recente do laravel 
https://laravel.com/docs/7.x/validation#using-extensions orienta-se carregar cada validação customizada com ` Validator::extend` dentro do boot() do service provider de bibliotecas com validações customizadas. Não testei, mas essa lib implementa exatamente dessa forma: https://github.com/robersonfaria/validation

**Comment by wallacemaxters** [comment]
Eu imaginei que em algum momento eu teria que pensar numa forma de reescrever esse código. Quando tive a ideia de desenvolvê-la, eu ainda utilizava o Laravel 4 e, com o tempo, foram surgindo adaptações para as novas versões. Vou pensar numa maneira bacana de reformular a escrita do código. 

Abraços.

**Comment by wallacemaxters** [comment]
@thiagogomesverissimo Boa tarde. Publicado no [dev-laravel-8]. Assim que eu terminar os testes individuais, publico uma versão para Laravel 6, 7 e 8. Como atualmente a lib está na versão 7.1, acho que, por bem, vou mudar para 8.0, por causa da grande alteração que foi feita

**Comment by wallacemaxters** [comment]
@thiagogomesverissimo Depois de tanto tempo, finalmente podemos dar as boas vindas pra versão [8.0](https://github.com/LaravelLegends/pt-br-validator/tree/8.0.0) do PtBrValidator. 

Agora, separei as classes, dando suporte não só ao `extend` da forma citada, mas também ao uso direto das regras de validação.

**Comment by thiagogomesverissimo** [comment]
Legal =)
