### ISSUE TITLE
Erro ao Validar CNPJ  com Mascara

### ISSUE THREAD

**Issue by helderjosex** [LaravelLegends/pt-br-validator#4]
Estou tentando validar o cnpj com máscara e o validate não está acusando erro. Como resolver?

```php
'cnpj'   => 'required|formato_cnpj|unique:table',
```

**Comment by wallacemaxters** [comment]
Qual é o problema especificamente? 

Existe dois validadores: formato_cnpj e cnpj. Um valida somente o formato, o outro valida se o CNPJ é válido.

**Comment by helderjosex** [comment]
Estou colocando no campo  o CNPJ dessa forma: 00.000.000/0000-00 e não está validando e salva.

**Comment by wallacemaxters** [comment]
Vou fazer uns testes aqui para verificar a situação.

**Comment by wallacemaxters** [comment]
O problema foi resolvido no commit 0a00c7d3b3ef429fced6857ec3ce4ceecf1a843a
