### ISSUE TITLE
Formato placa não atualizado para nova regra mercosul

### ISSUE THREAD

**Issue by excelentia** [LaravelLegends/pt-br-validator#42]
Segundo Nova regra do mercosul as placas agora podem ter também letras no segundo item da segunda string, ie:
FUM-0B05
FUM-5L58

**Comment by wallacemaxters** [comment]
Obrigado pela contribuição. Fiz um merge no pull request #35 para resolver o problema e adicionei os seus dados do issue como teste no código.
