### ISSUE TITLE
Arquivos de validação do PIS e do formato inexistentes.

### ISSUE THREAD

**Issue by CyberLPKF** [LaravelLegends/pt-br-validator#46]
Olá!

Primeiramente gostaria de parabenizá-lo pela sua iniciativa em montar este pacote para o Laravel.

Atualizei recentemente para a versão 8.0 via composer. Entretanto, os dois arquivos relativos a validação do PIS não encontram-se na pasta Rules juntamente com as demais regras.

Os arquivos que me refiro são Pis.php e FormatoPis.php

Utilizo o Laravel 7.29.3.

Já limpei o cache do artisan e do composer sem êxito.

Para corrigir fiz o seguinte:

- Baixei os arquivos manualmente daqui do github e salvei-os na pasta Rules
- Adicione as referidas chamadas no arquivo ValidatorProvider.

Após estas alterações, as validações passaram a funcionar.

Grato.

Luis

**Comment by wallacemaxters** [comment]
Boa tarde, @CyberLPKF . Eu esqueci de criar a tag com essa nova funcionalidae :droplet:. Vou fazer isso em breve.

**Comment by wallacemaxters** [comment]
Validação de PIS e Formato do Pis está presente agora na versão 8.0.1. Obrigado pelo retorno.
