### ISSUE TITLE
Validação cpf_or_cnpj

### ISSUE THREAD

**Issue by jrcristiano** [LaravelLegends/pt-br-validator#47]

**Comment by wallacemaxters** [comment]
Bom dia. Estarei avaliando a possibilidade da implementação da mesma. Obrigado pela contribuição

**Comment by wallacemaxters** [comment]
Foi adicionada na versão 8.0.2.

As classes adicionadas foram:

```php
\LaravelLegends\PtBrValidator\Rules\CpfOuCnpj::class
\LaravelLegends\PtBrValidator\Rules\FormatoCpfOuCnpj::class
```

E as validações adicionadas foram `cpf_ou_cnpj` e `formato_cpf_ou_cnpj`

**Comment by jrcristiano** [comment]
A comunidade sempre muito colaborativa, eu fico muito agradecido.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
