### ISSUE TITLE
Validação cpf_ou_cnpj não funciona

### ISSUE THREAD

**Issue by douglas-88** [LaravelLegends/pt-br-validator#49]
Bom dia a todos,

Estou tentendo usar a validação : "cpf_ou_cnpj" , porém me retorna esse erro: 
"Method LaravelLegends\\PtBrValidator\\Validator::validateCpfOuCnpj does not exist."

Obs: As demais regras funcionam.
Estou usando a versão 5.1.3 do pacote, e a versão do Laravel que estou usando é a 5.6.39.

Grato pela ajuda.

**Comment by ricocrivelli** [comment]
No arquivo `config/app.php` insira a linha abaixo no array `providers`:

`\LaravelLegends\PtBrValidator\ValidatorProvider::class,`


Deve ficar mais ou menos assim:

`'providers' => [
        \LaravelLegends\PtBrValidator\ValidatorProvider::class,
        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
...`

**Comment by wallacemaxters** [comment]
@douglas-88 de fato, essa versão não possui CpfOuCnpj. Vou implementá-la

**Comment by ArthurYdalgo** [comment]
> @douglas-88 de fato, essa versão não possui CpfOuCnpj. Vou implementá-la

Olá, Douglas. Vi que o último commit no repositório foi em janeiro, então imagino que esse método ainda não tenha sido implementado nessa versão. Pensei em fazer um PR pra fechar essa issue
