### ISSUE TITLE
O que acham de adicionar a validação para placa de carros?

### ISSUE THREAD

**Issue by wallacemaxters** [LaravelLegends/pt-br-validator#5]
Já que a ideia é colocar validações dos trecos brasileiros que usamos aqui, estava me questionando se não seria interessante também adicionar alguma validação para placas de carro.

O que acham?

**Comment by acwoss** [comment]
Uma possível solução:

```
public function validatePlacaDeCarro($value) {
    return preg_match('/^[a-zA-Z]{3}[\- ]?[0-9]{4}$/', $value) > 0;
}
```

Permitindo entradas nos formatos `abc-1234`, `abc 1234` e `abc1234`, não sendo sensível às maiúsculas.

Veja o teste: http://ideone.com/tPXEbF

**Comment by wallacemaxters** [comment]
Gostei da dica, mas eu acho uma boa remover o espaço :p
