### ISSUE TITLE
Suporte para Laravel 9

### ISSUE THREAD

**Issue by lucraraujo** [LaravelLegends/pt-br-validator#54]
A biblioteca não pode ser instalada no Laravel 9 por causa da dependência do illuminate/support desatualizada.

**Comment by utherbone** [comment]
É eu percebi isso, até tentei implementar manualemnte pelo source, mas sem sucesso! Seria  muito bom ver esse projeto sempre atualizado, mas o Laravel 8 ainda está firme e forte e só deve se tornar depreciado quando sair o Laravel 10.

**Comment by rodrigowbazevedo** [comment]
PR aberto e testado #55

**Comment by wallacemaxters** [comment]
Versão [https://github.com/LaravelLegends/pt-br-validator/tree/9.0.0](9.0.0) publicada =)
