### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by ednonunes2** [LaravelLegends/pt-br-validator#57]
Olá!
Desculpe sou iniciante.
Estou tendo dificuldades para utilizar o pacote, é só rodar o composer require(...) e pronto? Fiz isso mas continua em inglês.
Não precisa alterar o config/app ou ServiceProvider?
Uso o Laravel 9

Obrigado desde já e parabéns pelo projeto

**Comment by wallacemaxters** [comment]
Opa, bom demais? Na verdade, o Laravel PTBRValidator tem como finalidade apenas adicionar validações de "coisas brasileiras", e não traduzir as mensagens de validação. 

Por exemplo, você pode validar se um campo contém um cpf, pis ou cnpj válido.
