### ISSUE TITLE
CNPJ is not required

### ISSUE THREAD

**Issue by guilherme-lima-dev** [LaravelLegends/pt-br-validator#58]
I have field cnpj not required, but I want that when it is typed, the validation happens.

'cnpj' => 'cnpj|unique:administrator_personal_infos,cnpj',

**Comment by wallacemaxters** [comment]
Hello, you can speak in portugues here...

Você pode simplesmente adicionar o valor `nullable`.

Assim:

```php
'cnpj' => 'nullable|cnpj|unique:administrator_personal_infos,cnpj',
```

**Comment by guilherme-lima-dev** [comment]
Obrigado, eu achei uma outra solução, mas essa é bem melhor...
Fiz dessa maneira:

>  'cnpj' => ['unique:administrator_personal_infos', Rule::when($this->get('cnpj') != null, 'cnpj')],
