### ISSUE TITLE
Validações do objeto Password não está funcionando corretamente

### ISSUE THREAD

**Issue by Henriquex25** [LaravelLegends/pt-br-validator#61]
Não sei qual o motivo, mas todas as validações feitas utilizando o objeto Illuminate\Validation\Rules\Password não estão traduzindo as mensagens, na verdade somente a mensagem de caracteres mínimos está sendo traduzida.

Qualquer outra validação que não seja utilizando o objeto de validação de senha, está funcionando corretamente a tradução.

Estou utilizando a validação do Livewire, não sei se isso pode estar influenciando, mas qualquer outra validação que não seja de senha estão sendo traduzidas corretamente.

![image](https://user-images.githubusercontent.com/88984677/172769851-e1163242-8d86-46f4-a928-4f6bfb6e5225.png)

![image](https://user-images.githubusercontent.com/88984677/172769874-42ce26d3-8159-4a1e-9cb0-ebd68c115a63.png)

![image](https://user-images.githubusercontent.com/88984677/172769924-234bc495-54fd-4bcc-8078-1fbd3b222335.png)

Única validação funcionando :
![image](https://user-images.githubusercontent.com/88984677/172769966-5ddc7c13-84cf-4253-8f05-0268213daacd.png)

![image](https://user-images.githubusercontent.com/88984677/172770402-f0c5cfdc-95d1-4b77-971b-b1ba2b57beaf.png)

![image](https://user-images.githubusercontent.com/88984677/172770453-5c376701-6eca-49a6-9396-fe44532d8464.png)

Versões 

![image](https://user-images.githubusercontent.com/88984677/172770637-e6f52a16-12c4-4e6b-a6db-5fe640b6cc9e.png)

**Comment by wallacemaxters** [comment]
Olá, boa tarde.

A biblioteca do LaravelLegends/PtBrValidator refere-se a adição de validações comuns para dados brasileiros, como número de CPF, CNPJ, CEP e afins; Não se trata de adição de traduções de mensagens de validação.
