### ISSUE TITLE
Usar a validação de CPF e CNPJ no mesmo request

### ISSUE THREAD

**Issue by marfin-lab** [LaravelLegends/pt-br-validator#62]
É possível utilizar ambas validações, e ter uma condicional?
Preciso que seja ou um CPF ou um CNPJ válido. Mas, sou novo no Laravel, e não sei como realizar esta condicional.

`'document' => 'required|unique:companies|cnpj OU cpf',`

**Comment by wallacemaxters** [comment]
Olá, @marfin-lab. Desculpa a demora em responder, ando muito atarefado! 

A validação correspondente seria `cpf_ou_cnpj`
