### ISSUE TITLE
Release com suporte ao Laravel 10

### ISSUE THREAD

**Issue by EdyStauch** [LaravelLegends/pt-br-validator#67]
Estou atualizando minha aplicação para o Laravel 10 e o pt-br-validator está com problemas de dependências.

Parece que já foi feito um [commit](https://github.com/LaravelLegends/pt-br-validator/commit/50080f0f35d29872f240b060361981c74ddbc864)  atualizando as dependências.

Mas não tem um release novo com o suporte.

**Comment by lmpardini** [comment]
Também estou com problema parecido, uso em uma aplicação que está com laravel 9, mas estou trabalhando em uma nova que estou fazendo já com o 10, e não consigo implementar a bilbioteca.
