### ISSUE TITLE
Validação retornando erro quando CPF começa com 0

### ISSUE THREAD

**Issue by Geovanek** [LaravelLegends/pt-br-validator#71]
Olá,

Estou com um problema de validação de CPF quando este inicia com o número 0.

**Comment by Geovanek** [comment]
Resolvi tipando a variável como string, pois tipando como int o zero sempre sumia da frente.

**Comment by wallacemaxters** [comment]
Na verdade, o valor do CPF sempre precisará ser tratado como o tipo `string`, pois o PHP tratava números que iniciavam com `0` como o tipo `octa`, porém nas versões mais atuais ele simplesmente ignora o número `0`, o que faria com que seu CPF iniciado por `0` ficasse faltando um ou mais números, dependendo do número de zeros no início.

Quando for validar um CPF, evite utilizar validações do tipo `numeric`, pois acredito que internamente o Laravel converta o valor para int ou float.
